<?php

use Drupal\Core\Session\AccountInterface;
use Drupal\Core\Access\AccessResult;
use Drupal\Core\Asset\AttachedAssetsInterface;
use Drupal\block\BlockInterface;

/**
 * Implementation of hook_block_access()
 *
 * Blocks access to all blocks except the system_main_block
 * if the user does not have access to the current page.
 */
function restrict_visit_block_access(BlockInterface $block, $operation, AccountInterface $account)
{
	// if($operation == 'view')
	// {
	// 	if(\Drupal::service('restrict_visit.service')->userIsBlocked())
	// 	{
	// 		if($block->getPluginId() != 'system_main_block')
	// 		{
	// 			return AccessResult::forbidden();
	// 		}
	// 	}
	// }

	return AccessResult::neutral();
}

/**
 * Override of template_preprocess_page()
 *
 * This function unsets tabs and various
 * other page elements for blocked users
 * so they are not rendered
 */
function restrict_visit_preprocess_page(&$build)
{
	// if(\Drupal::service('restrict_visit.service')->userIsBlocked())
	// {
	// 	$regions = system_region_list(\Drupal::service('theme.manager')->getActiveTheme()->getName(), REGIONS_ALL);
	// 	unset($regions['content']);

	// 	$whitelisted_regions = Drupal::service('module_handler')->invokeAll('restrict_visit_whitelisted_regions');
	// 	foreach($whitelisted_regions as $wr)
	// 	{
	// 		unset($regions[$wr]);
	// 	}

	// 	foreach(array_keys($regions) as $region)
	// 	{
	// 		if(isset($build['page'][$region]))
	// 		{
	// 			unset($build['page'][$region]);
	// 		}
	// 	}

	// 	if(isset($build['tabs']))
	// 	{
	// 		if(isset($build['tabs']['#primary']))
	// 		{
	// 			$build['tabs']['#primary'] = [];
	// 		}
	// 		if(isset($build['tabs']['#secondary']))
	// 		{
	// 			$build['tabs']['#primary'] = [];
	// 		}
	// 	}
	// 	$build['title_prefix'] = [];
	// 	$build['title_suffix'] = [];
	// 	$build['main_menu'] = [];
	// 	$build['secondary_menu'] = [];
	// 	$build['action_links'] = [];
	// }
}

/**
 * Override of template_preprocess_html()
 *
 * This function unsets $page_top and $page_bottom
 * so that they are not passed to html.tpl.php,
 * preventing these regions from being rendered
 */
function restrict_visit_preprocess_html(&$build)
{
	// if(\Drupal::service('restrict_visit.service')->userIsBlocked())
	// {
	// 	if(isset($build['page_top']))
	// 	{
	// 		unset($build['page_top']);
	// 	}
	// 	if(isset($build['page_top']))
	// 	{
	// 		unset($build['page_bottom']);
	// 	}
	// }
}
